name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.wjmh }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@wjhm.dev '
          cd /var/www/wjmh
          git pull origin main
          sudo systemctl restart nginx
          '
